SUPABASE_URL = "https://hffrbskyjwmkurwwdzcj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmZnJic2t5andta3Vyd3dkemNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4OTAxMDAsImV4cCI6MjA5MjQ2NjEwMH0.RpMENU0oH7l__GjU-E9mE6GdUpAbIMWlt27zdOaB0JE"
GEMINI_API_KEY = "AIzaSyBm_tP0SlIJ86ERXcxMPZSvA7pEnfiPrqw"
